quick patch...?

diff --git a/install_fps_unlocker b/install_fps_unlocker
--- a/install_fps_unlocker
+++ b/install_fps_unlocker
@@ -19,14 +19,14 @@ if [ -z "$robloxPath" ]; then
         $robloxPath=$(find /Applications -name Roblox.app -print -quit 2>/dev/null)
         if [ -z "$robloxPath" ]; then
           $robloxPath=$(find ~/Applications -name Roblox.app -print -quit 2>/dev/null)
-        fi
-        if [ -z "$robloxPath" ]; then
-          echo "Roblox installation folder couldn't be found."
-          exit
+          if [ -z "$robloxPath" ]; then
+            echo "ERROR: Roblox installation folder couldn't be found."
+            exit 1
+          fi
         fi
       no)
-        echo "Roblox installation folder couldn't be found."
-        exit
+        echo "ERROR: Roblox installation folder couldn't be found."
+        exit 1
       *)
         echo "Unknown option."
         exit 1
