Patch #1
Full title:
Patch to actually check if the app exists or isn't empty

diff --git a/install_fps_unlocker b/install_fps_unlocker
--- a/install_fps_unlocker
+++ b/install_fps_unlocker
@@ -20,25 +20,30 @@ else
   targetFps=$1
 fi
 
-robloxPath="/Applications/Roblox.app"
+robloxPath="/Applications/Roblox.app/Contents"
 
-if [ -z "$robloxPath" ]; then
-  $robloxPath="~/Applications/Roblox.app"
-  if [ ! -d "$robloxPath" ]; then
-    $robloxPath="$HOME/Applications/Roblox.app"
+if [ ! -e "$robloxPath" ]; then
+  $robloxPath="~/Applications/Roblox.app/Contents"
+  if [ ! -e "$robloxPath" ]; then
+    $robloxPath="$HOME/Applications/Roblox.app/Contents"
   fi
-  if [ -z "$robloxPath" ]; then
+  if [ ! -e "$robloxPath" ]; then
     echo "WARNING: Couldn't find Roblox.app using default paths. Are you sure you want to use 'find' as a last resort? (yes/no)"
     read useFindMethod
     case $useFindMethod in
       yes)
         $robloxPath=$(find /Applications -name Roblox.app -print -quit 2>/dev/null)
-        if [ -z "$robloxPath" ]; then
+        if [ ! -e "$robloxPath" ]; then
           $robloxPath=$(find $HOME/Applications -name Roblox.app -print -quit 2>/dev/null)
-          if [ -z "$robloxPath" ]; then
+          if [ ! -e "$robloxPath" ]; then
             echo "ERROR: Roblox installation folder couldn't be found."
             exit 1
           fi
+        fi
+        $robloxPath+="/Contents"
+        if [ ! -e "$robloxPath" ]; then
+          echo "ERROR: Roblox installation folder couldn't be found."
+          exit 1
         fi
         ;;
       no)
@@ -53,7 +58,7 @@ if [ -z "$robloxPath" ]; then
   fi
 fi
 
-clientSettingsPath="$robloxPath/Contents/MacOS/ClientSettings"
+clientSettingsPath="$robloxPath/MacOS/ClientSettings"
 
 if [ ! -d "$clientSettingsPath" ]; then
   mkdir $clientSettingsPath
